### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#100]
Please can you make the following changes to text:

On the bathing water sign options page: 
The history of previous annual classifications?     becomes     Previous annual classifications
A map of the sampling point location?    becomes    A map of the sampling point location
The Environment Agency logo?     becomes     Environment Agency logo

On the PDF
Previous annual water-quality classifications        becomes    Previous annual classifications
Sampling Point Location     becomes     Sampling point location 
For more information (the second one )   becomes      Bathing water contact information

**Comment by ijdickinson** [comment]
@tamsinappleton Should be done now, if you could check

**Comment by tamsinappleton** [comment]
On the bathing water sign options page:
 
 The Environment Agency logo? becomes Environment Agency logo

Just deleting the The. It's a corporate style thing - they get very twitchy about us being The Environment Agency, and I know that's not the intention, but best to remove it. I'll raise a separate issue about the font at the end of the PDF

**Comment by tamsinappleton** [comment]
@ijdickinson Just making sure the comment above gets to you...

**Comment by ijdickinson** [comment]
Change deployed, if you'd like to test again.

**Comment by tamsinappleton** [comment]
Looks good.
