### ISSUE TITLE
Font size for contact information on PDF

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#102]
Can you shrink the contact information font size - or increase the field its in, so that it doesn't need to wrap around. We could do with the Email title and the actual email address being on the same line. If there isn't space, can the titles be removed so the email address and phone number are just displayed - they are self explanatory.

**Comment by ijdickinson** [comment]
@tamsinappleton I deployed a change last night, if you'd like to test it again please?

**Comment by tamsinappleton** [comment]
@ijdickinson I've just tested Christchurch Mudeford Sandbank East and put in a fake but probably realistic email address (I don't imagine they are that succinct). It does push the email onto two lines, and therefore off the page...

**Comment by ijdickinson** [comment]
@tamsinappleton OK, will investigate. What email address  did you use?

**Comment by tamsinappleton** [comment]
council@christchurchsandbanks.dorset.gov.uk

**Comment by ijdickinson** [comment]
@tamsinappleton I'm wondering about dropping the "Bathing water contact information" sub-title? As you said, it's pretty obvious that those are email addresses & phone numbers, and so it's (hopefully) obvious that it's contact information. 

That would allow us to reliably fit the email & phone on without having to drop the font size any further.

What do you think?

**Comment by tamsinappleton** [comment]
@ijdickinson Yep drop the sub-title.

**Comment by ijdickinson** [comment]
I've deployed a new version for testing.
