### ISSUE TITLE
2017 classification 

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#106]
Not sure if this is a bug or not - without Chris here to check what is sent over - but the overall classification is displaying 2016 classification for the current classification symbol. If it's something from staging that's fine, I can explain to Defra, just checking.

**Comment by ijdickinson** [comment]
@tamsinappleton I'm pretty certain we haven't published the 2017 classifications onto the staging server. I could get Stuart to look at doing that if you like, but I wonder if it's better not to try doing that just before the demo sesssion, in case anything goes amiss?

**Comment by tamsinappleton** [comment]
@ijdickinson Fine, I can explain that, leave as is.
