### ISSUE TITLE
Text changes - preview and download page / options page

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#111]
Pls can you make the following changes on the preview and download page

go to the next bathing water for X
becomes:
go to the next bathing water for local authority X 
(1. add local authority)

choose different sign options 
becomes:
choose different extra optional features
(2. change sign options to extra optional features)

And the following on the options page (this is the titel) 

Bathing water sign options for X
becomes:
Extra optional sign features for X

**Comment by ijdickinson** [comment]
Update deployed for testing

**Comment by tamsinappleton** [comment]
@ijdickinson You are right extra optional is too much of a mouthful/eyeful. 
However, rather than change to optional, please can you change these to extra. So 

choose different sign options
 becomes:
 choose different extra features
 (2. change sign options to extra features)

And the following on the options page (this is the title)

Bathing water sign options for X
 becomes:
 Extra sign features for X

**Comment by tamsinappleton** [comment]
@ijdickinson I'm closing this - it makes sense although it still doesn't quite look right - but don't need to mess with it forever. I'll check with Jonathan and let you know if we need a change.
