### ISSUE TITLE
Support link

### ISSUE THREAD

**Issue by ijdickinson** [DEFRA/bwq-signage#112]
Given that this is a new application, and we might expect a few teething issues, do you want a 'help' link on the site somewhere? Something like:

    If you have any questions or comments about this application, please contact us 
    at data.info@environment-agency.gov.uk

on the landing page perhaps?

**Comment by tamsinappleton** [comment]
@ijdickinson yes please!

**Comment by ijdickinson** [comment]
Update deployed for testing
