### ISSUE TITLE
Changes to monitoring statement

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#113]
Please can you change the monitoring statement at the top of all the of the signs (all that have them). 

From:
Water quality is monitored from May to September

To: 
Water quality is monitored by the Environment Agency from May to September

**Comment by ijdickinson** [comment]
Change deployed, but I'm not sure about it.

One of the challenges is that it looks wrong to have "Environment Agency" split over two lines:

    Water quality is monitored by the Environment 
               Agency from May to September

The alternative is to put a non-breaking space, but that leads to:

            Water quality is monitored by the
    Environment Agency from May to September

Where the second line is much longer. Not sure which you prefer?

Also, the flow of the copy feels a bit awkward. I wonder if it would be better as:

    Water quality is monitored between May and September
                  by the Environment Agency

?

**Comment by tamsinappleton** [comment]
@ijdickinson Agree - last version please

**Comment by ijdickinson** [comment]
@tamsinappleton Thanks, update deployed.

**Comment by tamsinappleton** [comment]
@ijdickinson Thanks but now I see it, can I be a pain and ask for the text to change back to from and to. So it's 

Water quality is monitored from May to September by the Environment Agency

**Comment by ijdickinson** [comment]
@tamsinappleton Updated

**Comment by tamsinappleton** [comment]
@ijdickinson Thanks
