### ISSUE TITLE
Classification symbols

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#114]
Defra have noticed the classification symbols are exactly as prescribed by the EU.
http://ec.europa.eu/environment/water/water-bathing/signs.htm
https://www.gov.uk/government/publications/water-quality-information-at-swimming-beaches-and-lakes-eu-regulations/water-quality-information-at-swimming-beaches-and-lakes
They've picked up on the missing bounding box (which I see isn't there if you download the PNG files from the gov.uk website, but I can't use illustrator on my computer so not sure what they're doing in that format). 
They've not mentioned the colour change - they should be all blue, or the missing text - they should have the excellent, good, sufficient, poor words next to the symbols on the right. But we should be making the sign do what the EU wants. 
They are wondering if it can be changed at this late stage, so let me know if it's a big issue to amend. I think the problem would be fitting the poor water sign next to the advice against bathing.

**Comment by ijdickinson** [comment]
I don't think the bounding box is part of the symbol, it's just there for exposition purposes on the page. See: http://ec.europa.eu/environment/water/water-bathing/pdf/baignade.pdf

**Comment by ijdickinson** [comment]
Similarly, if you download the source .eps files from the EU web site, they don't have a bounding box.

**Comment by tamsinappleton** [comment]
@ijdickinson I am checking with Defra, but given Jonathan's reaction I'm pretty sure we're going to have to change the symbols to match the EU, being blue with the key on the right. I'll get back to you in a while.

**Comment by tamsinappleton** [comment]
@ijdickinson Defra would like to see the symbols more closely reflect the EU versions, i.e. with key on the right and the blue colouring. Would you be able to make this change, in this hope this doesn't make it entirely squashed and unreadable.

**Comment by tamsinappleton** [comment]
@ijdickinson I should add, they're accepting bounding box not needed.

**Comment by ijdickinson** [comment]
Updated

**Comment by tamsinappleton** [comment]
Looks good. Thanks.

**Comment by tamsinappleton** [comment]
@ijdickinson Have just noticed something. Berrow North of Unity Farm seems to have larger stars on the key for the excellent than other BWs portrait A4 mode, if you flick between PDFs it becomes apparent. 
Also on Lulworth Cove, Maenporth... it's those with a Good classification.

**Comment by ijdickinson** [comment]
There was a small difference in the size of stars in the key. Fixed.
