### ISSUE TITLE
Previous year's classifications

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#115]
Have just been reminded, Jonathan only wanted 2015 and 2016 for this - in 2014 it wasn't a real classification as it was classified under the previous directive. 

Can 2014 be removed, so just display 2015 & 2016.

**Comment by ijdickinson** [comment]
Updated

**Comment by tamsinappleton** [comment]
@ijdickinson Thanks Ian. Can the blue of the stars be the same blue as that of the classification symbols? Otherwise have tested a couple with varying previous classifications, seem fine. I note that on the preview A4 portrait, it's variable which stay on a single line and which go into two lines, but on the PDF version everything consistently on two lines. Do I just chalk that up to preview expanding the page?

**Comment by ijdickinson** [comment]
Updated

The previous history was still allocating space for three years, even though it now only shows two.
