### ISSUE TITLE
Format of Environment Agency's Logo

### ISSUE THREAD

**Issue by CBUCKLEYBS9** [DEFRA/bwq-signage#120]
Hi @ijdickinson 

A local authority has asked for the format e.g. no. of pixels, format (jpg) etc of the Environment Agencies logo? Their aim is to mirror it for their local authority sign. 

Thanks 
Chris

**Comment by ijdickinson** [comment]
@CBUCKLEYBS9 45px. It doesn't really matter which format they use, but I'd generally suggest `.png` for small bitmap images.

**Comment by CBUCKLEYBS9** [comment]
@ijdickinson thanks very much
