### ISSUE TITLE
Feature: select a page size (A3 or A4)

### ISSUE THREAD

**Issue by ijdickinson** [DEFRA/bwq-signage#3]
*When* I am configuring a sign
*I can* choose A3 or A4 page size
*So that* I can select a sign that works best for the display at my bathing water

**Comment by ijdickinson** [comment]
@tamsinappleton I have deployed an initial version of this feature, but it will need some fine-tuning of font sizes etc.

Unfortunately, in order to get A3/A4 to work, I had to change some of the existing font sizes for A4. So it's possible that some of the currently fixed things, like long titles or long pollution source descriptions, will need to be revisited. Apologies, but a necessary evil!

Can you please test a range of bathing waters, and create tickets (or a ticket with a list of problems if you prefer) for any wonkily-sized elements you find?

**Comment by ijdickinson** [comment]
@tamsinappleton Any feedback from testing on A3?

**Comment by tamsinappleton** [comment]
@ijdickinson Seems fine to me. Happy to close if you like?

**Comment by ijdickinson** [comment]
Thanks. We can re-open if any problems arise.
