### ISSUE TITLE
Reduce font size for bathing waters with long names or descriptions

### ISSUE THREAD

**Issue by ijdickinson** [DEFRA/bwq-signage#64]
If we have a BW with a long name or description (thresholds to be determined), set a CSS class that reduces the font size to minimize overruns.

**Comment by tamsinappleton** [comment]
Tested Burnham Jetty North. Note seems fine on preview page, but still overruns on PDF.

**Comment by tamsinappleton** [comment]
Tested Porthcurno - portrait orientation. Seems fine on preview page, but overruns on PDF.

**Comment by ijdickinson** [comment]
@tamsinappleton This is somewhat improved now, but I think I can make it better. But Burham not so egregious now!

**Comment by tamsinappleton** [comment]
I've had to google egregious - so that's some education. 
I've just tested Christchurch Mudeford Sandbank East - the title still I think knocking the rest right out of shape - the title goes across three lines in portrait mode.

**Comment by tamsinappleton** [comment]
@ijdickinson 
ah, I've remembered to make sure the comment reaches you...

**Comment by ijdickinson** [comment]
@tamsinappleton Thanks, I'll have a look. Unless ... I don't suppose it's possible to rename that BW? :smiley:

**Comment by ijdickinson** [comment]
@tamsinappleton I deployed a change last night, if you'd like to test again.

**Comment by tamsinappleton** [comment]
Titles working better, we do need to look at font overall

**Comment by tamsinappleton** [comment]
Tested Studland Knoll House. A4, portrait, the title is too large, pushing the classification symbol over the fields below.

**Comment by ijdickinson** [comment]
There was an issue with a missing font-file on the server, affecting the generated pdfs. Hopefully this is resolved now.

**Comment by ijdickinson** [comment]
Update deployed for testing.

**Comment by tamsinappleton** [comment]
Tested: Studland Knoll Beach, Clacton Martello Tower, Porthcurno, Cotswold Country Park. A4 portrait and landscape. 
All seem fine.
