### ISSUE TITLE
Task: investigate IE11 failings

### ISSUE THREAD

**Issue by ijdickinson** [DEFRA/bwq-signage#76]
@CBUCKLEYBS9 reported some residual layout bugs on IE11. Need to investigate and fix.

**Comment by tamsinappleton** [comment]
@ijdickinson IEs has been looking OK apart from the BW name overlaying the classification symbol - think you've rectified that now. I'll have a good look tomorrow but can't think of anything else offhand.

**Comment by tamsinappleton** [comment]
@ijdickinson I'm closing this - I've had a good look this morning in IE (and in Chrome), all seems to be presenting and working fine.
