### ISSUE TITLE
Error message - no logo was updated

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#95]
Having chosen Lynmouth, with an enhanced sign design (but not selecting a logo), when I click back to select an alternative bathing water, or alternative options, I get an error message "Something went wrong: No image file was uploaded"

Have attached word doc if needed

[Issue tja01.docx](https://github.com/DEFRA/bwq-signage/files/1739827/Issue.tja01.docx)

**Comment by ijdickinson** [comment]
@tamsinappleton I think that the fix I just put in for ticket #94 has also fixed this issue. Can you please try again? You will need to refresh the page to reload the application.

**Comment by tamsinappleton** [comment]
Seems fine now.
