### ISSUE TITLE
Classification symbol cut short on PDF

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#96]
The text from the EU classification symbol cut off on the PDF

**Comment by ijdickinson** [comment]
@tamsinappleton I think I have finally nailed this one!

**Comment by tamsinappleton** [comment]
Tested Porthcurno (excellent) and Combe Martin (sufficient) and they're not displaying properly... sorry...

**Comment by tamsinappleton** [comment]
@ijdickinson Just making sure the comment above gets to you...

**Comment by ijdickinson** [comment]
@tamsinappleton I have made a further change, if you could please test again.

**Comment by tamsinappleton** [comment]
Tested Hope Cove, looks good
