### ISSUE TITLE
Maps - display changed between preview and PDF

### ISSUE THREAD

**Issue by tamsinappleton** [DEFRA/bwq-signage#97]
Maps (Lowestoft north of Clairmont pier) tested - map on PDF is more zoomed in on PDF than it appears on the preview page. 

The preview page is the correct display.

**Comment by ijdickinson** [comment]
@tamsinappleton Should be working now

**Comment by tamsinappleton** [comment]
Checked in IE and chrome, seem fine.

**Comment by tamsinappleton** [comment]
Seems to be back again! Only for A4 versions, the maps appear to be more zoomed in on the PDF version that the preview. The A3 versions seems to print as displayed on the preview.
Same on IE and Chrome. 

Tested Studland Knoll House.

**Comment by ijdickinson** [comment]
@tamsinappleton The zoom level is the same, the difference is that the bounding box is a different size so more of the map is showing in the preview. In both cases, preview and pdf, the centre-point is the sampling point, the zoom level is the same, and we show as much of the surrounding area as we can given the constraints of the poster.

I've picked a zoom-level that gives a reasonable balance between detail and extent. We could change the zoom (for all maps) to show more of the area, but at correspondingly less detail.

**Comment by ijdickinson** [comment]
OK, let's close for now and re-open if we get pushback.
